### Pandas
pandas a python library that is extensively used for data analytics, ML and other Data fields  
It provides possibility to organise data into something called Dataframe, which acts as a table of data (2D)  
It is organised into rows and columns with named indices

In [18]:
import pandas as pd

In [19]:
# Create a data frame using the pandas function
DF = pd.DataFrame ({
                    'Name' : ['Vishnu', "Ram", 'Bharat'], 
                    'Id' : [234, 201, 78],
                    'Course' : ['ML', 'GenAI', "Python"],
                    'Batch' : ['C1', 'C2', 'C1']})
DF

     Name   Id  Course Batch
0  Vishnu  234      ML    C1
1     Ram  201   GenAI    C2
2  Bharat   78  Python    C1

In [20]:
# Let us understand how is it organised
print ("Data type : \n", DF.dtypes)

print ("Index : \n", DF.index)

print ("Number of Records : \n", len(DF))

print ("Number of Fields : \n", len(DF.columns))

Data type :
 Name      object
Id         int64
Course    object
Batch     object
dtype: object
Index :
 RangeIndex(start=0, stop=3, step=1)
Number of Records :
 3
Number of Fields :
 4

In [31]:
# Access specific Column
Names = DF['Name']

print ("Type : \n", type (Names))
print ("Content : \n",  Names)
print(DF.Name)

Type :
 <class 'pandas.core.series.Series'>
Content :
 0    Vishnu
1       Ram
2    Bharat
3    Dileep
4     Phani
Name: Name, dtype: object
0    Vishnu
1       Ram
2    Bharat
3    Dileep
4     Phani
Name: Name, dtype: object

In [22]:
# Access specific Row
Rec_1 = DF.iloc [1] # Access a row based on the index position

print ("Type : \n", type (Rec_1))
print ("Content : \n",  Rec_1)

Type :
 <class 'pandas.core.series.Series'>
Content :
 Name        Ram
Id          201
Course    GenAI
Batch        C2
Name: 1, dtype: object

In [ ]:
# Make specific Column in a data frame
Names = DF[['Name']]

print ("Length : \n", len (Names))
print ("Content : \n",  Names)

Length :
 5
Content :
 0    Vishnu
1       Ram
2    Bharat
3    Dileep
4     Phani
Name: Name, dtype: object

In [24]:
# Filter out rows based on condition
Filtered = DF[DF['Batch'] == 'C1']
Filtered

     Name   Id  Course Batch
0  Vishnu  234      ML    C1
2  Bharat   78  Python    C1

In [25]:
# Update an exising column values : just an assignment
print(DF['Id'])
DF['Id'] = [145, 156, 88]
DF

0    234
1    201
2     78
Name: Id, dtype: int64

     Name   Id  Course Batch
0  Vishnu  145      ML    C1
1     Ram  156   GenAI    C2
2  Bharat   88  Python    C1

In [26]:
# Add another column, again just like a variable assignment
DF ['Score'] = [78, 85, 80]
DF

     Name   Id  Course Batch  Score
0  Vishnu  145      ML    C1     78
1     Ram  156   GenAI    C2     85
2  Bharat   88  Python    C1     80

In [27]:
# Add Rows by concatenating
new_rec = pd.DataFrame ({
                        'Name' : ['Dileep', 'Phani'],
                        'Id' : [101, 102],
                        'Course' : ['GenAI', 'ML'],
                        'Batch' : ['C1', 'C2'],
                        'Score' : [80, 75]
})
new_rec

     Name   Id Course Batch  Score
0  Dileep  101  GenAI    C1     80
1   Phani  102     ML    C2     75

In [28]:
DF = pd.concat ([DF, new_rec], ignore_index=True)
DF

     Name   Id  Course Batch  Score
0  Vishnu  145      ML    C1     78
1     Ram  156   GenAI    C2     85
2  Bharat   88  Python    C1     80
3  Dileep  101   GenAI    C1     80
4   Phani  102      ML    C2     75

In [29]:
# Aggregating functions. See how the column is accessed
print ("Min Score : ", DF.Score.min())
print ("Max Score : ", DF.Score.max())
print ("Mean Score : ", DF.Score.mean())
print ("Median Score : ", DF.Score.median())

Min Score :  75
Max Score :  85
Mean Score :  79.6
Median Score :  80.0

In [32]:
# Check the Max score per course : Use Group by
grp = DF.groupby ('Course') ['Score'].max ().rename ("Max ")
grp

Course
GenAI     85
ML        78
Python    80
Name: Max , dtype: int64

In [33]:
# Read data from a CSV file into Data Frame
Index_Data = pd.read_csv ('Index.csv')
print (Index_Data.dtypes)

Index Name     object
Date           object
Open          float64
High          float64
Low           float64
Close         float64
dtype: object

In [34]:
# Change the Date field to datetime type
Index_Data['Date'] = pd.to_datetime(Index_Data['Date'])
print (Index_Data.dtypes)
Index_Data

Index Name            object
Date          datetime64[ns]
Open                 float64
High                 float64
Low                  float64
Close                float64
dtype: object

    Index Name       Date      Open      High       Low     Close
0     NIFTY 50 2025-06-13  24473.00  24754.35  24473.00  24718.60
1     NIFTY 50 2025-06-12  25164.45  25196.20  24825.90  24888.20
2     NIFTY 50 2025-06-11  25134.15  25222.40  25081.30  25141.40
3     NIFTY 50 2025-06-10  25196.05  25199.30  25055.45  25104.25
4     NIFTY 50 2025-06-09  25160.10  25160.10  25077.15  25103.20
..         ...        ...       ...       ...       ...       ...
252   NIFTY 50 2024-06-07  22821.85  23320.20  22789.05  23290.15
253   NIFTY 50 2024-06-06  22798.60  22910.15  22642.60  22821.40
254   NIFTY 50 2024-06-05  22128.35  22670.40  21791.95  22620.35
255   NIFTY 50 2024-06-04  23179.50  23179.50  21281.45  21884.50
256   NIFTY 50 2024-06-03  23337.90  23338.70  23062.30  23263.90

[257 rows x 6 columns]

In [35]:
# Identify the days where Close price is higher than open.
# By filtering

Green_Days = Index_Data.loc [Index_Data['Close'] > Index_Data ['Open'], :]
print (len(Green_Days))
Green_Days

113

    Index Name       Date      Open      High       Low     Close
0     NIFTY 50 2025-06-13  24473.00  24754.35  24473.00  24718.60
2     NIFTY 50 2025-06-11  25134.15  25222.40  25081.30  25141.40
5     NIFTY 50 2025-06-06  24748.70  25029.50  24671.45  25003.05
6     NIFTY 50 2025-06-05  24691.20  24899.85  24613.10  24750.90
7     NIFTY 50 2025-06-04  24560.45  24644.25  24530.45  24620.20
..         ...        ...       ...       ...       ...       ...
242   NIFTY 50 2024-06-24  23382.30  23558.10  23350.00  23537.85
247   NIFTY 50 2024-06-14  23464.95  23490.40  23334.25  23465.60
252   NIFTY 50 2024-06-07  22821.85  23320.20  22789.05  23290.15
253   NIFTY 50 2024-06-06  22798.60  22910.15  22642.60  22821.40
254   NIFTY 50 2024-06-05  22128.35  22670.40  21791.95  22620.35

[113 rows x 6 columns]

In [38]:
# Identify the days where Close price is at least 0.5% higher than the Open price
Proper_Green_Days = Index_Data [Index_Data['Close'] > (Index_Data ['Open'] * 1.005)]
Proper_Green_Days = Proper_Green_Days.sort_values (by='Date', ascending=True)

print (len(Proper_Green_Days))
Proper_Green_Days

49

    Index Name       Date      Open      High       Low     Close
254   NIFTY 50 2024-06-05  22128.35  22670.40  21791.95  22620.35
252   NIFTY 50 2024-06-07  22821.85  23320.20  22789.05  23290.15
242   NIFTY 50 2024-06-24  23382.30  23558.10  23350.00  23537.85
241   NIFTY 50 2024-06-25  23577.10  23754.15  23562.05  23721.30
240   NIFTY 50 2024-06-26  23723.10  23889.90  23670.45  23868.80
239   NIFTY 50 2024-06-27  23881.55  24087.45  23805.40  24044.50
237   NIFTY 50 2024-07-01  23992.95  24164.00  23992.70  24141.95
225   NIFTY 50 2024-07-18  24543.80  24837.75  24504.45  24800.85
220   NIFTY 50 2024-07-25  24230.95  24426.15  24210.80  24406.10
219   NIFTY 50 2024-07-26  24423.35  24861.15  24410.90  24834.85
205   NIFTY 50 2024-08-16  24334.85  24563.90  24204.50  24541.15
186   NIFTY 50 2024-09-12  25059.65  25433.35  24941.45  25388.90
180   NIFTY 50 2024-09-20  25525.95  25849.25  25426.60  25790.95
176   NIFTY 50 2024-09-26  26005.40  26250.90  25998.40  26216.05
169   NIFTY 50 2024-10-08  24832.20  25044.00  24756.80  25013.15
161   NIFTY 50 2024-10-18  24664.95  24886.20  24567.65  24854.05
154   NIFTY 50 2024-10-29  24328.85  24484.50  24140.85  24466.85
149   NIFTY 50 2024-11-05  23916.50  24229.05  23842.75  24213.30
148   NIFTY 50 2024-11-06  24308.75  24537.60  24204.05  24484.05
138   NIFTY 50 2024-11-22  23411.80  23956.10  23359.00  23907.25
133   NIFTY 50 2024-11-29  23927.15  24188.45  23927.15  24131.10
132   NIFTY 50 2024-12-02  24140.85  24301.70  24008.65  24276.05
129   NIFTY 50 2024-12-05  24539.15  24857.75  24295.55  24708.40
123   NIFTY 50 2024-12-13  24498.35  24792.30  24180.80  24768.30
110   NIFTY 50 2025-01-02  23783.00  24226.70  23751.55  24188.65
91    NIFTY 50 2025-01-29  23026.75  23183.35  22976.50  23163.10
89    NIFTY 50 2025-01-31  23296.75  23546.80  23277.40  23508.40
86    NIFTY 50 2025-02-04  23509.90  23762.75  23423.15  23739.25
77    NIFTY 50 2025-02-17  22809.90  22974.20  22725.45  22959.50
66    NIFTY 50 2025-03-05  22073.05  22394.90  22067.80  22337.30
62    NIFTY 50 2025-03-11  22345.95  22522.10  22314.70  22497.90
59    NIFTY 50 2025-03-17  22353.15  22577.00  22353.15  22508.75
58    NIFTY 50 2025-03-18  22662.25  22857.80  22599.20  22834.30
56    NIFTY 50 2025-03-20  23036.60  23216.70  22973.95  23190.65
55    NIFTY 50 2025-03-21  23168.25  23402.70  23132.80  23350.40
54    NIFTY 50 2025-03-24  23515.40  23708.75  23433.50  23658.35
51    NIFTY 50 2025-03-27  23433.95  23646.45  23412.20  23591.95
48    NIFTY 50 2025-04-02  23192.60  23350.00  23158.45  23332.35
45    NIFTY 50 2025-04-07  21758.40  22254.00  21743.65  22161.60
42    NIFTY 50 2025-04-11  22695.40  22923.90  22695.40  22828.55
39    NIFTY 50 2025-04-17  23401.85  23872.35  23298.55  23851.65
38    NIFTY 50 2025-04-21  23949.15  24189.55  23903.65  24125.55
33    NIFTY 50 2025-04-28  24070.25  24355.10  24054.05  24328.50
27    NIFTY 50 2025-05-07  24233.30  24449.60  24220.00  24414.40
24    NIFTY 50 2025-05-12  24420.10  24944.80  24378.85  24924.70
21    NIFTY 50 2025-05-15  24694.45  25116.25  24494.45  25062.10
15    NIFTY 50 2025-05-23  24639.50  24909.05  24614.05  24853.15
5     NIFTY 50 2025-06-06  24748.70  25029.50  24671.45  25003.05
0     NIFTY 50 2025-06-13  24473.00  24754.35  24473.00  24718.60

In [ ]:
# Identify the Previous day close, by shifting
Index_Data.sort_values (by='Date', inplace=True)
Index_Data ['PDC'] = Index_Data['Close'].shift (1)
Index_Data

    Index Name       Date      Open      High       Low     Close       PDC
256   NIFTY 50 2024-06-03  23337.90  23338.70  23062.30  23263.90       NaN
255   NIFTY 50 2024-06-04  23179.50  23179.50  21281.45  21884.50  23263.90
254   NIFTY 50 2024-06-05  22128.35  22670.40  21791.95  22620.35  21884.50
253   NIFTY 50 2024-06-06  22798.60  22910.15  22642.60  22821.40  22620.35
252   NIFTY 50 2024-06-07  22821.85  23320.20  22789.05  23290.15  22821.40
..         ...        ...       ...       ...       ...       ...       ...
4     NIFTY 50 2025-06-09  25160.10  25160.10  25077.15  25103.20  25003.05
3     NIFTY 50 2025-06-10  25196.05  25199.30  25055.45  25104.25  25103.20
2     NIFTY 50 2025-06-11  25134.15  25222.40  25081.30  25141.40  25104.25
1     NIFTY 50 2025-06-12  25164.45  25196.20  24825.90  24888.20  25141.40
0     NIFTY 50 2025-06-13  24473.00  24754.35  24473.00  24718.60  24888.20

[257 rows x 7 columns]

In [43]:
# identify the gap up days (at least .5% from previous day close)
Gap_Up_Days = Index_Data[Index_Data['Open'] > (Index_Data['PDC'] * 1.005)]
print (len(Gap_Up_Days))
Gap_Up_Days

25

    Index Name       Date      Open      High       Low     Close       PDC
254   NIFTY 50 2024-06-05  22128.35  22670.40  21791.95  22620.35  21884.50
253   NIFTY 50 2024-06-06  22798.60  22910.15  22642.60  22821.40  22620.35
248   NIFTY 50 2024-06-13  23480.95  23481.05  23353.90  23398.90  23322.95
235   NIFTY 50 2024-07-03  24291.75  24309.15  24207.10  24286.50  24123.85
212   NIFTY 50 2024-08-06  24189.85  24382.60  23960.40  23992.55  24055.60
211   NIFTY 50 2024-08-07  24289.40  24337.70  24184.90  24297.50  23992.55
209   NIFTY 50 2024-08-09  24386.85  24419.75  24311.20  24367.50  24117.00
205   NIFTY 50 2024-08-16  24334.85  24563.90  24204.50  24541.15  24143.75
186   NIFTY 50 2024-09-12  25059.65  25433.35  24941.45  25388.90  24918.45
137   NIFTY 50 2024-11-25  24253.55  24351.55  24135.45  24221.90  23907.25
136   NIFTY 50 2024-11-26  24343.30  24343.30  24125.40  24194.50  24221.90
117   NIFTY 50 2024-12-23  23738.20  23869.55  23647.20  23753.45  23587.50
100   NIFTY 50 2025-01-16  23377.25  23391.65  23272.05  23311.80  23213.20
92    NIFTY 50 2025-01-28  22960.45  23137.95  22857.65  22957.25  22829.15
86    NIFTY 50 2025-02-04  23509.90  23762.75  23423.15  23739.25  23361.05
65    NIFTY 50 2025-03-06  22476.35  22556.45  22245.85  22544.70  22337.30
58    NIFTY 50 2025-03-18  22662.25  22857.80  22599.20  22834.30  22508.75
56    NIFTY 50 2025-03-20  23036.60  23216.70  22973.95  23190.65  22907.60
54    NIFTY 50 2025-03-24  23515.40  23708.75  23433.50  23658.35  23350.40
44    NIFTY 50 2025-04-08  22446.75  22697.20  22270.85  22535.85  22161.60
42    NIFTY 50 2025-04-11  22695.40  22923.90  22695.40  22828.55  22399.15
41    NIFTY 50 2025-04-15  23368.35  23368.35  23207.00  23328.55  22828.55
36    NIFTY 50 2025-04-23  24357.60  24359.30  24119.95  24328.95  24167.25
24    NIFTY 50 2025-05-12  24420.10  24944.80  24378.85  24924.70  24008.00
4     NIFTY 50 2025-06-09  25160.10  25160.10  25077.15  25103.20  25003.05